### ISSUE TITLE
NoSuchElementException with a basic exemple

### ISSUE THREAD

**Issue by fistons** [ma1uta/jmsdk#12]
Using this code sample

```java
package net.pedr0.matrixbot;

import io.github.ma1uta.matrix.client.StandaloneClient;

public class Application {
  public static void main(String[] args) {
    StandaloneClient mxClient = new StandaloneClient.Builder()
        .domain("pedr0.net")
        .build();
    
    mxClient.auth().login("bot", "password".toCharArray());
    mxClient.profile().setDisplayName("BotBot");

    String roomId = mxClient.room().joinByIdOrAlias("#test:pedr0.net", null, null).getRoomId();
    
    mxClient.event().sendMessage(roomId, "Hello, World!");
    
    mxClient.auth().logout();
  }
}
```

I have this exception

```
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.ServiceLoader$2.next(ServiceLoader.java:1308)
	at java.base/java.util.ServiceLoader$2.next(ServiceLoader.java:1296)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at io.github.ma1uta.matrix.client.AbstractHomeServerResolver.<init>(AbstractHomeServerResolver.java:83)
	at io.github.ma1uta.matrix.client.ClientHomeServerResolver.<init>(ClientHomeServerResolver.java:32)
	at io.github.ma1uta.matrix.client.MatrixClient.<init>(MatrixClient.java:95)
	at io.github.ma1uta.matrix.client.StandaloneClient.<init>(StandaloneClient.java:42)
	at io.github.ma1uta.matrix.client.StandaloneClient.<init>(StandaloneClient.java:38)
	at io.github.ma1uta.matrix.client.StandaloneClient$Builder.newInstance(StandaloneClient.java:125)
	at io.github.ma1uta.matrix.client.StandaloneClient$Builder.newInstance(StandaloneClient.java:121)
	at io.github.ma1uta.matrix.client.AbstractClientBuilder.build(AbstractClientBuilder.java:73)
	at net.pedr0.matrixbot.Application.main(Application.java:9)
```

Using java 11, client-impl 0.12.0 and a matrix synapse server 1.18.0

**Comment by ma1uta** [comment]
Adding the https://mvnrepository.com/artifact/io.github.ma1uta.matrix/jackson-support/0.12.0 will fix this issue.
Also you can review examples: https://github.com/ma1uta/matrix-client-example

**Comment by fistons** [comment]
Oh, I knew I missed something! Works like a charm, thanks!
